package com.howtodoinjava.entity;
// Generated Feb 28, 2017 9:07:39 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set teoremas = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    
    	
    public Categoria(int id, String nombre, Set teoremas) {
        this.id = id;
        this.nombre = nombre;
        this.teoremas = teoremas;
    
    }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

   
    public Set getTeoremas() {
        return this.teoremas;
    }
    
    public void setTeoremas(Set teoremas) {
        this.teoremas = teoremas;
    }


}



