package com.howtodoinjava.entity;
// Generated Feb 28, 2017 9:07:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Resuelve generated by hbm2java
 */
public class Resuelve  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private Teorema teorema;
     private String teoserializadoizq;
     private String teoserializadoder;
     private String nombreteorema;
     private String numeroteorema;
     private boolean resuelto;
     private Set solucions = new HashSet(0);

    public Resuelve() {
    }

	
    public Resuelve(int id, Usuario usuario, Teorema teorema, String teoserializadoizq, String teoserializadoder, String numeroteorema, boolean resuelto) {
        this.id = id;
        this.usuario = usuario;
        this.teorema = teorema;
        this.teoserializadoizq = teoserializadoizq;
        this.teoserializadoder = teoserializadoder;
        this.numeroteorema = numeroteorema;
        this.resuelto = resuelto;
    }
    public Resuelve(int id, Usuario usuario, Teorema teorema, String teoserializadoizq, String teoserializadoder, String nombreteorema, String numeroteorema, boolean resuelto, Set solucions) {
       this.id = id;
       this.usuario = usuario;
       this.teorema = teorema;
       this.teoserializadoizq = teoserializadoizq;
       this.teoserializadoder = teoserializadoder;
       this.nombreteorema = nombreteorema;
       this.numeroteorema = numeroteorema;
       this.resuelto = resuelto;
       this.solucions = solucions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Teorema getTeorema() {
        return this.teorema;
    }
    
    public void setTeorema(Teorema teorema) {
        this.teorema = teorema;
    }
    public String getTeoserializadoizq() {
        return this.teoserializadoizq;
    }
    
    public void setTeoserializadoizq(String teoserializadoizq) {
        this.teoserializadoizq = teoserializadoizq;
    }
    public String getTeoserializadoder() {
        return this.teoserializadoder;
    }
    
    public void setTeoserializadoder(String teoserializadoder) {
        this.teoserializadoder = teoserializadoder;
    }
    public String getNombreteorema() {
        return this.nombreteorema;
    }
    
    public void setNombreteorema(String nombreteorema) {
        this.nombreteorema = nombreteorema;
    }
    public String getNumeroteorema() {
        return this.numeroteorema;
    }
    
    public void setNumeroteorema(String numeroteorema) {
        this.numeroteorema = numeroteorema;
    }
    public boolean isResuelto() {
        return this.resuelto;
    }
    
    public void setResuelto(boolean resuelto) {
        this.resuelto = resuelto;
    }
    public Set getSolucions() {
        return this.solucions;
    }
    
    public void setSolucions(Set solucions) {
        this.solucions = solucions;
    }




}


