package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA


import com.howtodoinjava.lambdacalculo.PasoInferencia;
import java.util.ArrayList;
import java.util.List;
import org.springframework.util.SerializationUtils;




/**
 * Solucion generated by hbm2java
 */
public class Solucion  implements java.io.Serializable {
   
     private SolucionId id;
     private Resuelve resuelve;
     private byte[] arregloSerializado;
     private List<PasoInferencia> arregloInferencias;

    public Solucion() {
        this.arregloInferencias = new ArrayList<PasoInferencia>();
    }

     
    public Solucion(Resuelve resuelve, List<PasoInferencia> arregloInferencias) {
        this.resuelve = resuelve;
        this.arregloSerializado = SerializationUtils.serialize(arregloInferencias);
        this.arregloInferencias = arregloInferencias;
    }

    public void setId(SolucionId id) {
        this.id = id;
    }

    public void setResuelve(Resuelve resuelve) {
        this.resuelve = resuelve;
    }

    public void setArregloSerializado(byte[] arregloSerializado) {
        this.arregloSerializado = arregloSerializado;
    }

    public void setArregloInferencias(List<PasoInferencia> arregloInferencias) {
        this.arregloInferencias = arregloInferencias;
        this.arregloSerializado = SerializationUtils.serialize(arregloInferencias);
    }
    
    public void addArregloInferencias(PasoInferencia paso) {
        this.arregloInferencias.add(paso);
    }
    public SolucionId getId() {
        return id;
    }

    public Resuelve getResuelve() {
        return resuelve;
    }

    public byte[] getArregloSerializado() {
        return arregloSerializado;
    }

    public List<PasoInferencia> getArregloInferencias() {
        return arregloInferencias;
    }
    

}


