package com.howtodoinjava.entity;
// Generated Feb 28, 2017 9:07:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Teorema generated by hbm2java
 */
public class Teorema  implements java.io.Serializable {


     private int id;
     private String enunciadoizq;
     private String enunciadoder;
     private Set resuelves = new HashSet(0);

    public Teorema() {
    }

	
    public Teorema(int id, String enunciadoizq, String enunciadoder) {
        this.id = id;
        this.enunciadoizq = enunciadoizq;
        this.enunciadoder = enunciadoder;
    }
    public Teorema(int id, String enunciadoizq, String enunciadoder, Set resuelves) {
       this.id = id;
       this.enunciadoizq = enunciadoizq;
       this.enunciadoder = enunciadoder;
       this.resuelves = resuelves;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEnunciadoizq() {
        return this.enunciadoizq;
    }
    
    public void setEnunciadoizq(String enunciadoizq) {
        this.enunciadoizq = enunciadoizq;
    }
    public String getEnunciadoder() {
        return this.enunciadoder;
    }
    
    public void setEnunciadoder(String enunciadoder) {
        this.enunciadoder = enunciadoder;
    }
    public Set getResuelves() {
        return this.resuelves;
    }
    
    public void setResuelves(Set resuelves) {
        this.resuelves = resuelves;
    }
    
}


