package com.howtodoinjava.entity;
// Generated Mar 20, 2017 12:50:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import org.springframework.util.SerializationUtils;

/**
 * Teorema generated by hbm2java
 */
public class Teorema  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue( strategy= GenerationType.SEQUENCE, generator="teorema_id_seq")
    @SequenceGenerator(name="teorema_id_seq", sequenceName="teorema_id_seq")
     private int id;
     private Categoria categoria;
     private String enunciadoizq;
     private String enunciadoder;
     private byte[] teoserializadoizq;
     private byte[] teoserializadoder;
     private boolean ocultartrue;
     private boolean esquema;
     private Set resuelves = new HashSet(0);

    public Teorema() {
    }

    public Teorema(Categoria categoria, String enunciadoizq, String enunciadoder, byte[] teoserializadoizq, byte[] teoserializadoder, boolean ocultartrue, boolean esquema) {
        this.categoria = categoria;
        this.enunciadoizq = enunciadoizq;
        this.enunciadoder = enunciadoder;
        this.teoserializadoizq = teoserializadoizq;
        this.teoserializadoder = teoserializadoder;
        this.ocultartrue = ocultartrue;
        this.esquema = esquema;
    }


    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getEnunciadoizq() {
        return this.enunciadoizq;
    }
    
    public void setEnunciadoizq(String enunciadoizq) {
        this.enunciadoizq = enunciadoizq;
    }
    public String getEnunciadoder() {
        return this.enunciadoder;
    }
    
    public void setEnunciadoder(String enunciadoder) {
        this.enunciadoder = enunciadoder;
    }
    public boolean isOcultartrue() {
        return this.ocultartrue;
    }
    
    public void setOcultartrue(boolean ocultartrue) {
        this.ocultartrue = ocultartrue;
    }

    public void setTeoserializadoizq(byte[] teoserializadoizq) {
        this.teoserializadoizq = ((byte[])SerializationUtils.serialize(this.getTeoserializadoizq()));
    }

    public void setTeoserializadoder(byte[] teoserializadoder) {
        this.teoserializadoder = ((byte[])SerializationUtils.serialize(this.getTeoserializadoder()));
    }

    public void setResuelves(Set resuelves) {
        this.resuelves = resuelves;
    }

    public byte[] getTeoserializadoizq() {
        return teoserializadoizq;
    }

    public byte[] getTeoserializadoder() {
        return teoserializadoder;
    }

    public Set getResuelves() {
        return resuelves;
    }

    public boolean isEsquema() {
        return esquema;
    }

    public void setEsquema(boolean esquema) {
        this.esquema = esquema;
    }

}


