package com.howtodoinjava.entity;
// Generated 27/06/2014 08:05:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

    @Length(min=3, max=20, message="login debe tener entre 3 y 20 caracteres")
    @Pattern(regexp="^[a-zA-Z0-9]+$",message="login debe ser alphanumerico sin espacios")
     private String login;
    @NotEmpty
     private String nombre;
     private String apellido;
     @Email
     private String correo;
     @Length(min=6, max=20,message="El password debe tener al menos 6 caracteres.")     
     private String password;
     private Set<Termino> terminos = new HashSet<Termino>(0);
     private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);

    public Usuario() {
    }

	
    public Usuario(String login) {
        this.login = login;
    }
    public Usuario(String login, String nombre, String apellido, String correo, String password, Set<Termino> terminos, Set<Publicacion> publicacions) {
       this.login = login;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.password = password;
       this.terminos = terminos;
       this.publicacions = publicacions;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Termino> getTerminos() {
        return this.terminos;
    }
    
    public void setTerminos(Set<Termino> terminos) {
        this.terminos = terminos;
    }
    public Set<Publicacion> getPublicacions() {
        return this.publicacions;
    }
    
    public void setPublicacions(Set<Publicacion> publicacions) {
        this.publicacions = publicacions;
    }

    @Override
    public boolean equals(Object u)
    {
        return this.getLogin().equals(((Usuario)u).getLogin());
    }


}


